AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DBSchema:
    Type: String
    Default: users

Resources:
  DBBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DBBuildRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: "*"
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource: "*"

  # BastionSecurityGroup:
  #   Type: AWS::EC2::SecurityGroup
  #   Properties:
  #     GroupDescription: "Allow SSH Access to Bastion Host"
  #     VpcId: !ImportValue GlobalVPCID
  #     SecurityGroupIngress:
  #       - IpProtocol: tcp
  #         FromPort: !Ref DBPort
  #         ToPort: !Ref DBPort
  #         CidrIp: !ImportValue PrivateSubnetACidrBlock
  #       - IpProtocol: tcp
  #         FromPort: !Ref DBPort
  #         ToPort: !Ref DBPort
  #         CidrIp: !ImportValue PrivateSubnetBCidrBlock

  DBBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: UsersBuildProject
      Source:
        Type: GITHUB
        Location: https://github.com/dmytro-kucherenko/smartner-api-gateway  # Param to reuse
        BuildSpec: project.yaml   # Param to reuse
      SourceVersion: initial-setup # Param to reuse
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/go:1.17
        Type: LINUX_CONTAINER
        # EnvironmentVariables: # From env
        #   - Name: DB_USERNAME
        #     Value: !Sub "{{resolve:secretsmanager:/db:SecretString:username:AWSCURRENT}}"
        #   - Name: DB_PASSWORD
        #     Value: !Sub "{{resolve:secretsmanager:/db:SecretString:password:AWSCURRENT}}"
        #   - Name: DB_HOST
        #     Value: !GetAtt UsersDBInstance.Endpoint.Address
        #   - Name: DB_PORT
        #     Value: !GetAtt UsersDBInstance.Endpoint.Port
        #   - Name: DB_NAME
        #     Value: !Sub "{{resolve:secretsmanager:/db:SecretString:name:AWSCURRENT}}"
        #   - Name: DB_SCHEMA
        #     Value: !Ref DBSchema
      ServiceRole: !Ref DBBuildRole
      Artifacts:
        Type: NO_ARTIFACTS
      TimeoutInMinutes: 60
      VpcConfig:
        SubnetIds:
          - !ImportValue PrivateSubnetAID
          - !ImportValue PrivateSubnetBID
        # SecurityGroupIds:
        #   - !ImportValue DBSecurityGroupID

Outputs:
  DBBuildProjectName:
    Description: "Name of DB Build Project"
    Value: !Ref DBBuildProjectName
